---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
    version: v1
  name: my-app
spec:
  replicas: 9
  selector:
    matchLabels:
      app: my-app
      version: v1
  template:
    metadata:
      labels:
        app: my-app
        version: v1
    spec:
      containers:
        - image: nginx:1.21
          name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app-v2
    version: v2
  name: my-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-v2
      version: v2
  template:
    metadata:
      labels:
        app: my-app-v2
        version: v2
    spec:
      containers:
        - image: nginx:latest
          name: nginx
